### ISSUE TITLE
Use "Zepto.extend" instead of "$.extend" (to work 'noConflict' like)

### ISSUE THREAD

**Issue by headjump** [dcompute/Zepto-Cookie#1]
Hi, 

I'd like to use your plugin for a project, but I've got one problem with it: Zepto only uses $ if it isn't used before.

See this fragment from the Zepto js code:

```
'$' in window || (window.$ = Zepto);
```

Could you please use

```
Zepto.extend(...
```

... instead of $.extend, so nothing breaks even if some other framework uses '$'

Thanks,
Dennis

**Comment by dcompute** [comment]
Updated to use the longhand syntax now. Thanks for noticing!
